//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L1.Features.OWCommunicators.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OWErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OWErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L1.Features.OWCommunicators.Resources.OWErrors", typeof(OWErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect login name or password..
        /// </summary>
        internal static string _2001 {
            get {
                return ResourceManager.GetString("2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been closed. Please contact your upline for details, thank you..
        /// </summary>
        internal static string _2002 {
            get {
                return ResourceManager.GetString("2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. Please contact CSD for details, thank you..
        /// </summary>
        internal static string _2003 {
            get {
                return ResourceManager.GetString("2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your IP address is restricted..
        /// </summary>
        internal static string _2004 {
            get {
                return ResourceManager.GetString("2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been closed. Please contact CSD for details..
        /// </summary>
        internal static string _2005 {
            get {
                return ResourceManager.GetString("2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has Insufficient funds. .
        /// </summary>
        internal static string _3002 {
            get {
                return ResourceManager.GetString("3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your stake had exceeded your bet limit settings, please try again..
        /// </summary>
        internal static string _3003 {
            get {
                return ResourceManager.GetString("3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game disabled. Please contact your upline for details, thank you..
        /// </summary>
        internal static string _3004 {
            get {
                return ResourceManager.GetString("3004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win limit hit! Please contact your upline, thank you..
        /// </summary>
        internal static string _3006 {
            get {
                return ResourceManager.GetString("3006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose limit hit ! Please contact your upline, thank you..
        /// </summary>
        internal static string _3007 {
            get {
                return ResourceManager.GetString("3007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no bet limit setting for this game, please contact your upline to set it..
        /// </summary>
        internal static string _3008 {
            get {
                return ResourceManager.GetString("3008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bet limit had been updated, please try again.
        /// </summary>
        internal static string _3009 {
            get {
                return ResourceManager.GetString("3009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been suspended. Please contact your upline for details, thank you..
        /// </summary>
        internal static string _3010 {
            get {
                return ResourceManager.GetString("3010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been suspended. Please contact your upline for details, thank you..
        /// </summary>
        internal static string _3013 {
            get {
                return ResourceManager.GetString("3013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is unavailable at the moment. Please contact CSD for details, thank you..
        /// </summary>
        internal static string _3014 {
            get {
                return ResourceManager.GetString("3014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was not found..
        /// </summary>
        internal static string _4012 {
            get {
                return ResourceManager.GetString("4012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error..
        /// </summary>
        internal static string _5002 {
            get {
                return ResourceManager.GetString("5002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is under maintenance..
        /// </summary>
        internal static string _5003 {
            get {
                return ResourceManager.GetString("5003", resourceCulture);
            }
        }
    }
}
